const rooms=[['vault','THE VAULT','Chips, trophies, prizes and Full Tilt history.'],['control','CONTROL ROOM','Security feeds, servers and building controls.'],['high','HIGH ROLLER ROOM','Private tables. Expensive mistakes.'],['office','BACK OFFICE','Paperwork, cash counter and things nobody explains.'],['casino','CASINO FLOOR','The heart of Headquarters. No evidence is hidden here.'],['after','AFTERHOURS','Bar, pool table, couches and abandoned drinks.'],['workshop','WORKSHOP','Repairs, tools and unfinished projects.'],['kitchen','KITCHEN','Takeout, dirty dishes and one deeply suspicious pot.'],['back','BACK ROOM','Nobody seems willing to explain this room.']];
const suspects=['Sam','Kass','Michael','Ruby','Seal','Kate','REM','Tweeky'];
const weapons=['Casino Chips','Ban Hammer','Broken Bottle','Pool Cue','Ethernet Cable','Trophy','Wrench','Heavy Ashtray','Letter Opener'];
const crimeRooms=rooms.filter(r=>r[0]!=='casino').map(r=>r[1]);
const adj={vault:['control','office'],control:['vault','high','casino'],high:['control','after'],office:['vault','casino','workshop'],casino:['control','office','after','kitchen'],after:['high','casino','back'],workshop:['office','kitchen'],kitchen:['workshop','casino','back'],back:['kitchen','after']};
const securityConfigs=[{name:'OPEN FLOOR',blocked:[]},{name:'NORTH LOCKDOWN',blocked:[['vault','control'],['control','high']]},{name:'SERVICE LOCKDOWN',blocked:[['office','workshop'],['kitchen','back']]},{name:'EAST LOCKDOWN',blocked:[['high','after'],['after','back']]}];
const startRooms=['vault','high','office','after','workshop','kitchen','back','control'];
const shuffle=a=>[...a].sort(()=>Math.random()-.5),d6=()=>1+Math.floor(Math.random()*6),$=id=>document.getElementById(id),roomName=id=>rooms.find(r=>r[0]===id)[1];
const solution={killer:suspects[Math.floor(Math.random()*suspects.length)],weapon:weapons[Math.floor(Math.random()*weapons.length)],room:crimeRooms[Math.floor(Math.random()*crimeRooms.length)]};
const deck=shuffle([...suspects.filter(x=>x!==solution.killer).map(name=>({type:'SUSPECT',name})),...weapons.filter(x=>x!==solution.weapon).map(name=>({type:'WEAPON',name})),...crimeRooms.filter(x=>x!==solution.room).map(name=>({type:'ROOM',name}))]);
const players=suspects.map((name,i)=>({name,room:startRooms[i],role:name===solution.killer?'KILLER':'INVESTIGATOR',hand:[],found:{},suggestions:0,wrongAccusations:0,accuseLocked:false,revealedHand:false}));
deck.forEach((c,i)=>players[i%players.length].hand.push(c));

function makeClues(){
 const s=shuffle(suspects.filter(x=>x!==solution.killer)),w=shuffle(weapons.filter(x=>x!==solution.weapon)),r=shuffle(crimeRooms.filter(x=>x!==solution.room));
 return [
  {axis:'killer',text:`The Killer is NOT ${s.slice(0,3).join(', ')}.`,test:c=>!s.slice(0,3).includes(c.killer)},
  {axis:'killer',text:`The Killer is NOT ${s.slice(3,6).join(', ')}.`,test:c=>!s.slice(3,6).includes(c.killer)},
  {axis:'killer',text:`The Killer is one of: ${shuffle([solution.killer,s[0],s[1]]).join(', ')}.`,test:c=>[solution.killer,s[0],s[1]].includes(c.killer)},
  {axis:'weapon',text:`The murder weapon was NOT ${w.slice(0,3).join(', ')}.`,test:c=>!w.slice(0,3).includes(c.weapon)},
  {axis:'weapon',text:`The murder weapon was NOT ${w.slice(3,6).join(', ')}.`,test:c=>!w.slice(3,6).includes(c.weapon)},
  {axis:'weapon',text:`The weapon is one of: ${shuffle([solution.weapon,w[0],w[1]]).join(', ')}.`,test:c=>[solution.weapon,w[0],w[1]].includes(c.weapon)},
  {axis:'room',text:`The crime did NOT happen in ${r.slice(0,4).join(', ')}.`,test:c=>!r.slice(0,4).includes(c.room)},
  {axis:'room',text:`The crime happened in one of: ${shuffle([solution.room,r[0],r[1],r[2]]).join(', ')}.`,test:c=>[solution.room,r[0],r[1],r[2]].includes(c.room)}
 ];
}
function candidateCases(){return suspects.flatMap(k=>weapons.flatMap(w=>crimeRooms.map(r=>({killer:k,weapon:w,room:r}))))}
function validateClues(set){const survivors=candidateCases().filter(c=>set.every(cl=>cl.test(c)));return survivors.length===1&&survivors[0].killer===solution.killer&&survivors[0].weapon===solution.weapon&&survivors[0].room===solution.room}
let clueDefs=makeClues();for(let tries=0;tries<20&&!validateClues(clueDefs);tries++)clueDefs=makeClues();
if(!validateClues(clueDefs))throw new Error('Evidence generator failed uniqueness validation.');
const searchable=rooms.filter(r=>r[0]!=='casino').map(r=>r[0]),generatedClues=shuffle(clueDefs.map(x=>x.text)),clueMap=Object.fromEntries(searchable.map((r,i)=>[r,generatedClues[i]]));

let state={turn:0,round:1,public:[],passages:true,security:0,phase:'START',moveRoll:0,reachable:{},acted:false,gameOver:false,publicHands:[]};
const me=()=>players[state.turn],edgeKey=(a,b)=>[a,b].sort().join('|');
function blocked(a,b){return securityConfigs[state.security].blocked.some(e=>edgeKey(...e)===edgeKey(a,b))}
function neighbors(id){let n=adj[id].filter(x=>!blocked(id,x));if(state.passages){if(id==='vault')n.push('back');if(id==='back')n.push('vault');if(id==='high')n.push('workshop');if(id==='workshop')n.push('high')}return [...new Set(n)]}
function reachablePaths(start,maxSteps){const found={},queue=[[start,[]]];const best={[start]:0};while(queue.length){const [node,path]=queue.shift();if(path.length>=maxSteps)continue;for(const next of neighbors(node)){const np=[...path,next],dist=np.length;if(best[next]!==undefined&&best[next]<=dist)continue;best[next]=dist;if(next!==start)found[next]=np;queue.push([next,np])}}return found}
function knowledge(p){return Math.min(8,new Set([...Object.values(p.found),...state.public]).size)}
function canAccuse(p){return knowledge(p)>=3&&!p.accuseLocked&&!state.gameOver}

function render(){
 const p=me(),board=$('board');board.innerHTML='';
 rooms.forEach(([id,n,d])=>{const occupants=players.filter(x=>x.room===id),path=state.phase==='MOVE'?state.reachable[id]:null;const el=document.createElement('div');el.className='room '+(id==='casino'?'center ':'')+(p.room===id?'current ':'')+(path?'reachable ':'');let extra=occupants.map(x=>`<span class="token">${x.name}${x===p?' • TURN':''}</span>`).join('');if(path)extra+=`<span class="route">${path.length} STEP${path.length===1?'':'S'}</span>`;if(['vault','back','high','workshop'].includes(id))extra+=`<span class="passage">◈ PASSAGE ${state.passages?'OPEN':'LOCKED'}</span>`;el.innerHTML=`<h2>${n}</h2><p>${d}</p>${extra}`;el.onclick=()=>move(id);board.appendChild(el)});
 $('location').textContent=roomName(p.room);$('round').textContent=`ROUND ${state.round}`;$('conference').textContent=`CASE CONFERENCE IN ${5-(state.round%5)||5} · ${securityConfigs[state.security].name}`;$('turnOwner').textContent=`${p.name}'S TURN`;$('roleTitle').textContent=p.role;$('roleText').textContent=p.role==='KILLER'?'You know WHO: you. You do NOT know WHERE or WITH WHAT. Solve your own crime and cover your tracks.':'Find WHO killed them, WHERE it happened, and WITH WHAT.';
 $('rollBtn').disabled=state.phase!=='START'||state.gameOver;$('searchBtn').disabled=p.room==='casino'||state.acted||state.phase==='MOVE'||state.gameOver;$('suggestBtn').disabled=p.room==='casino'||state.acted||state.phase==='MOVE'||state.gameOver;$('flipBtn').classList.toggle('hidden',p.room!=='control');$('flipBtn').disabled=state.acted||state.phase==='MOVE'||state.gameOver;$('endBtn').disabled=state.phase==='MOVE'||state.gameOver;$('accuseBtn').disabled=!canAccuse(p);$('accuseBtn').textContent=canAccuse(p)?(p.role==='KILLER'?'🩸 COVER YOUR TRACKS':'⚠ MAKE ACCUSATION'):`🔒 ACCUSATION LOCKED (${knowledge(p)}/3)`;
 $('movement').textContent=state.phase==='MOVE'?`Movement roll: ${state.moveRoll}. Choose any highlighted destination within range. Security and passage state are already calculated into the route.`:'';renderPlayers();renderPrivate();
}
function renderPlayers(){$('players').innerHTML=players.map((p,i)=>`<span class="${i===state.turn?'active-player':''}">${p.name} · ${roomName(p.room)}${p.revealedHand?' · HAND EXPOSED':''}</span>`).join('')}
function renderPrivate(){const p=me();$('handCount').textContent=`${p.hand.length} CARDS`;$('hand').innerHTML=p.hand.map(c=>`<div class="clue"><b>${c.type}</b> — ${c.name}</div>`).join('')||'<em>No cards.</em>';const entries=Object.entries(p.found);$('evidenceCount').textContent=`${entries.length} / 8`;$('notebook').innerHTML=entries.length?entries.map(([r,c])=>`<div class="clue">${c}<em>Recovered in ${roomName(r)}</em></div>`).join(''):'No evidence recovered yet.';$('publicCount').textContent=`${state.public.length} / 8`;$('caseBoard').innerHTML=(state.public.length?state.public.map(c=>`<div class="clue">${c}<em>Origin: UNKNOWN</em></div>`).join(''):'Nothing has entered the public record.')+(state.publicHands.length?state.publicHands.map(h=>`<div class="clue"><b>EXPOSED HAND</b> — ${h}</div>`).join(''):'');const k=knowledge(p);$('knowledge').textContent=`${k} / 8`;$('knowledgeText').textContent=p.accuseLocked?'Your accusation privilege is locked. Recover a NEW private room clue to earn it back.':k>=3?'You have enough verified case knowledge to risk an accusation.':`${3-k} more unique verified clue${3-k===1?'':'s'} before accusation unlocks.`;$('knowledgeBar').style.width=`${k/8*100}%`}

function rollMove(){if(state.phase!=='START')return;state.moveRoll=d6();state.reachable=reachablePaths(me().room,state.moveRoll);state.phase='MOVE';const count=Object.keys(state.reachable).length;msg(`🎲 ${state.moveRoll}. ${count?`Choose one of ${count} reachable destinations.`:'No legal route. You may remain here and investigate.'}`);if(!count)state.phase='ROOM';render()}
function move(to){if(state.phase!=='MOVE')return;const path=state.reachable[to];if(!path)return msg('That destination is outside your current legal movement range.');const from=me().room;me().room=to;state.phase='ROOM';state.reachable={};msg(`${me().name} traveled ${roomName(from)} → ${path.map(roomName).join(' → ')}.`);render()}
function search(){const p=me();if(p.room==='casino'||state.acted||state.phase==='MOVE')return;state.acted=true;const r=d6(),wasNew=!p.found[p.room];if(r===1||r===6){p.found[p.room]=clueMap[p.room];if(wasNew&&p.accuseLocked){p.accuseLocked=false;msg(`🎲 ${r} — SUCCESS. New evidence recovered. Your accusation privilege is restored.`)}else if(wasNew)msg(`🎲 ${r} — SUCCESS. New evidence recovered privately.`);else msg(`🎲 ${r} — SUCCESS, but you already knew this room's evidence.`)}else msg(`🎲 ${r} — NOTHING. Sorry about your luck.`);render()}
function openSwitch(){if(me().room==='control'&&!state.acted&&state.phase!=='MOVE')$('switchModal').classList.remove('hidden')}
function flip(type){$('switchModal').classList.add('hidden');state.acted=true;const r=d6();if(r!==1&&r!==6){msg(`🎲 ${r} — FAILED. Nobody else knows you tried.`);return render()}if(type==='passages'){state.passages=!state.passages;msg(`🎲 ${r} — SUCCESS. HIDDEN PASSAGES ${state.passages?'OPENED':'LOCKED'}.`)}else{state.security=(state.security+1)%securityConfigs.length;msg(`🎲 ${r} — SUCCESS. SECURITY CONFIGURATION CHANGED: ${securityConfigs[state.security].name}.`)}render()}
function openSuggestion(){if(me().room==='casino'||state.acted||state.phase==='MOVE')return;$('suspectSelect').innerHTML=suspects.map(x=>`<option>${x}</option>`).join('');$('weaponSelect').innerHTML=weapons.map(x=>`<option>${x}</option>`).join('');$('suggestModal').classList.remove('hidden')}
function suggest(){const p=me(),s=$('suspectSelect').value,w=$('weaponSelect').value,r=roomName(p.room);$('suggestModal').classList.add('hidden');state.acted=true;p.suggestions++;let shown=null,who=null;for(let step=1;step<players.length;step++){const q=players[(state.turn+step)%players.length],matches=q.hand.filter(c=>c.name===s||c.name===w||c.name===r);if(matches.length){shown=matches[Math.floor(Math.random()*matches.length)];who=q;break}}msg(shown?`${who.name} privately disproved your suggestion: ${shown.type} — ${shown.name}.`:`Nobody could disprove ${s} + ${w} + ${r}. 👀`);render()}
function openAccuse(){const p=me();if(!canAccuse(p))return;$('accuseSuspect').innerHTML=suspects.map(x=>`<option ${p.role==='KILLER'&&x===p.name?'selected':''}>${x}</option>`).join('');$('accuseSuspect').disabled=p.role==='KILLER';$('accuseWeapon').innerHTML=weapons.map(x=>`<option>${x}</option>`).join('');$('accuseRoom').innerHTML=crimeRooms.map(x=>`<option>${x}</option>`).join('');$('accuseTitle').textContent=p.role==='KILLER'?'COVER YOUR TRACKS':'MAKE AN ACCUSATION';$('accuseHelp').textContent=p.role==='KILLER'?'Name the weapon and crime scene before the investigators identify you.':'Commit to Killer + Weapon + Room. A wrong accusation exposes information and locks you out until you recover a NEW private room clue.';$('accuseModal').classList.remove('hidden')}
function accuse(){const p=me(),s=p.role==='KILLER'?p.name:$('accuseSuspect').value,w=$('accuseWeapon').value,r=$('accuseRoom').value;$('accuseModal').classList.add('hidden');if(s===solution.killer&&w===solution.weapon&&r===solution.room){state.gameOver=true;showModal('CASE CLOSED',p.role==='KILLER'?'THE KILLER COVERED THEIR TRACKS.':'THE KILLER HAS BEEN CAUGHT.',`<p><b>${solution.killer}</b> · <b>${solution.weapon}</b> · <b>${solution.room}</b></p><p>${p.name} wins.</p>`);return render()}p.wrongAccusations++;p.accuseLocked=true;state.acted=true;const penalty=d6();if(penalty===1||penalty===6){p.hand=[];msg(`WRONG. Penalty roll ${penalty}: your hand is discarded face-down. Nobody learns those cards. Recover a NEW private room clue to earn another accusation.`)}else{const revealed=p.hand.map(c=>`${c.type}: ${c.name}`).join(' · ')||'EMPTY HAND';p.revealedHand=true;if(!state.publicHands.includes(`${p.name}: ${revealed}`))state.publicHands.push(`${p.name}: ${revealed}`);msg(`WRONG. Penalty roll ${penalty}: YOUR HAND IS REVEALED. Recover a NEW private room clue to earn another accusation.`)}render()}
function endTurn(){state.turn=(state.turn+1)%players.length;state.phase='START';state.moveRoll=0;state.reachable={};state.acted=false;if(state.turn===0){state.round++;if(state.round%5===0)conference()}msg(`${me().name}'s turn. Roll movement.`);render()}
function conference(){const discovered=[...new Set(players.flatMap(p=>Object.values(p.found)))].filter(c=>!state.public.includes(c));let c,source;if(discovered.length){c=discovered[Math.floor(Math.random()*discovered.length)];source='A player with unrevealed evidence is forced to testify.'}else{const unseen=Object.values(clueMap).filter(x=>!state.public.includes(x));if(unseen.length){c=unseen[Math.floor(Math.random()*unseen.length)];source='No player could produce fresh testimony. Headquarters triggers a forensic sweep instead.'}}if(c){state.public.push(c);showModal('⚠ CASE CONFERENCE','EVIDENCE ENTERED INTO THE RECORD',`<p>${source}</p><p><b>${c}</b></p><p><em>The room it came from remains secret.</em></p>`)}else showModal('⚠ CASE CONFERENCE','THE CASE BOARD IS COMPLETE','<p>All eight verified evidence clues are already public. Somebody should probably solve the damn murder.</p>')}
function showModal(e,t,html){$('modalEyebrow').textContent=e;$('modalTitle').textContent=t;$('modalText').innerHTML=html;$('modal').classList.remove('hidden')}function msg(t){$('rollResult').textContent=t}
$('rollBtn').onclick=rollMove;$('searchBtn').onclick=search;$('suggestBtn').onclick=openSuggestion;$('flipBtn').onclick=openSwitch;$('accuseBtn').onclick=openAccuse;$('endBtn').onclick=endTurn;$('submitSuggestion').onclick=suggest;$('cancelSuggestion').onclick=()=> $('suggestModal').classList.add('hidden');$('switchDoors').onclick=()=>flip('doors');$('switchPassages').onclick=()=>flip('passages');$('cancelSwitch').onclick=()=> $('switchModal').classList.add('hidden');$('submitAccuse').onclick=accuse;$('cancelAccuse').onclick=()=> $('accuseModal').classList.add('hidden');$('closeModal').onclick=()=> $('modal').classList.add('hidden');render();