const rooms=[['vault','THE VAULT','Chips, trophies, prizes and Full Tilt history.'],['control','CONTROL ROOM','Security feeds, servers and building controls.'],['high','HIGH ROLLER ROOM','Private tables. Expensive mistakes.'],['office','BACK OFFICE','Paperwork, cash counter and things nobody explains.'],['casino','CASINO FLOOR','The heart of Headquarters. No evidence is hidden here.'],['after','AFTERHOURS','Bar, pool table, couches and abandoned drinks.'],['workshop','WORKSHOP','Repairs, tools and unfinished projects.'],['kitchen','KITCHEN','Takeout, dirty dishes and one deeply suspicious pot.'],['back','BACK ROOM','Nobody seems willing to explain this room.']];
const clues=["The murder weapon was NOT Casino Chips, the Broken Bottle, or the Wrench.","The Killer is NOT Sam, Michael, or Ruby.","The crime did NOT happen in The Vault, Workshop, or Back Office.","The weapon was one of: Ban Hammer, Pool Cue, Trophy, or Heavy Ashtray.","The Killer is one of: Kass, Seal, Kate, or Sam.","The crime happened in one of: Afterhours, Kitchen, High Roller Room, or Back Room.","The weapon was NOT the Ethernet Cable or Letter Opener.","The Killer is NOT Kate or Seal."];
const searchable=rooms.filter(r=>r[0]!=='casino').map(r=>r[0]);
const shuffled=[...clues].sort(()=>Math.random()-.5);const clueMap=Object.fromEntries(searchable.map((r,i)=>[r,shuffled[i]]));
const adj={vault:['control','office'],control:['vault','high','casino'],high:['control','after'],office:['vault','casino','workshop'],casino:['control','office','after','kitchen'],after:['high','casino','back'],workshop:['office','kitchen'],kitchen:['workshop','casino','back'],back:['kitchen','after']};
let state={room:'casino',round:1,found:{},public:[],passages:true,security:0,acted:false};
const $=id=>document.getElementById(id);const name=id=>rooms.find(r=>r[0]===id)[1];
function render(){const board=$('board');board.innerHTML='';rooms.forEach(([id,n,d])=>{const el=document.createElement('div');el.className='room '+(id==='casino'?'center ':'')+(state.room===id?'current':'');let extras=state.room===id?'<span class="token">YOU ARE HERE</span>':'';if(['vault','back','high','workshop'].includes(id))extras+=`<span class="passage">◈ PASSAGE ${state.passages?'OPEN':'LOCKED'}</span>`;el.innerHTML=`<h2>${n}</h2><p>${d}</p>${extras}`;el.onclick=()=>move(id);board.appendChild(el)});$('location').textContent=name(state.room);$('round').textContent='ROUND '+state.round;$('conference').textContent='CASE CONFERENCE IN '+(5-(state.round%5)||5);$('searchBtn').disabled=state.room==='casino'||state.acted;$('flipBtn').classList.toggle('hidden',state.room!=='control');$('flipBtn').disabled=state.acted;renderNotes()}
function move(to){if(state.acted)return msg('You already acted this turn. End your turn first.');let legal=adj[state.room].includes(to);if(state.passages&&((state.room==='vault'&&to==='back')||(state.room==='back'&&to==='vault')||(state.room==='high'&&to==='workshop')||(state.room==='workshop'&&to==='high')))legal=true;if(!legal)return msg('That room is not reachable from here.');state.room=to;state.acted=true;msg('Moved to '+name(to)+'.');render()}
function search(){if(state.room==='casino'||state.acted)return;state.acted=true;const roll=1+Math.floor(Math.random()*6);if(roll===1||roll===6){state.found[state.room]=clueMap[state.room];msg(`🎲 ${roll} — SUCCESS. Evidence recovered privately.`)}else msg(`🎲 ${roll} — NOTHING. Sorry about your luck.`);render()}
function flip(){if(state.room!=='control'||state.acted)return;const type=Math.random()<.5?'passages':'doors';const roll=1+Math.floor(Math.random()*6);state.acted=true;if(roll===1||roll===6){if(type==='passages'){state.passages=!state.passages;msg(`🎲 ${roll} — SWITCH FLIPPED. Hidden passages are now ${state.passages?'OPEN':'LOCKED'}.`)}else{state.security=(state.security+1)%3;msg(`🎲 ${roll} — SWITCH FLIPPED. Security configuration changed.`)}}else msg(`🎲 ${roll} — FAILED. Nobody else knows you tried.`);render()}
function endTurn(){state.round++;state.acted=false;msg('New round. Choose your move.');if(state.round%5===0)conference();render()}
function conference(){const available=Object.values(state.found).filter(c=>!state.public.includes(c));if(available.length){const c=available[Math.floor(Math.random()*available.length)];state.public.push(c);$('modalText').innerHTML=`A verified clue has been forced into the public record:<br><br><b>${c}</b><br><br><em>The room it came from remains secret.</em>`}else $('modalText').textContent='No one at this table can currently produce a new verified clue. The investigation continues.';$('modal').classList.remove('hidden')}
function renderNotes(){const entries=Object.entries(state.found);$('evidenceCount').textContent=entries.length+' / 8';$('notebook').className=entries.length?'':'empty';$('notebook').innerHTML=entries.length?entries.map(([r,c])=>`<div class="clue">${c}<em>Recovered in ${name(r)}</em></div>`).join(''):'No evidence recovered yet.';$('publicCount').textContent=state.public.length+' / 8';$('caseBoard').innerHTML=state.public.length?state.public.map(c=>`<div class="clue">${c}<em>Origin: UNKNOWN</em></div>`).join(''):'Nothing has entered the public record.'}
function msg(t){$('rollResult').textContent=t}$('searchBtn').onclick=search;$('flipBtn').onclick=flip;$('endBtn').onclick=endTurn;$('closeModal').onclick=()=> $('modal').classList.add('hidden');render();