const rooms=[['vault','THE VAULT','Chips, trophies, prizes and Full Tilt history.'],['control','CONTROL ROOM','Security feeds, servers and building controls.'],['high','HIGH ROLLER ROOM','Private tables. Expensive mistakes.'],['office','BACK OFFICE','Paperwork, cash counter and things nobody explains.'],['casino','CASINO FLOOR','The heart of Headquarters. No evidence is hidden here.'],['after','AFTERHOURS','Bar, pool table, couches and abandoned drinks.'],['workshop','WORKSHOP','Repairs, tools and unfinished projects.'],['kitchen','KITCHEN','Takeout, dirty dishes and one deeply suspicious pot.'],['back','BACK ROOM','Nobody seems willing to explain this room.']];
const suspects=['Sam','Kass','Michael','Ruby','Seal','Kate','REM','Tweeky'];
const weapons=['Casino Chips','Ban Hammer','Broken Bottle','Pool Cue','Ethernet Cable','Trophy','Wrench','Heavy Ashtray','Letter Opener'];
const crimeRooms=rooms.filter(r=>r[0]!=='casino').map(r=>r[1]);
const clues=["The murder weapon was NOT Casino Chips, Broken Bottle, or Wrench.","The Killer is NOT Sam, Michael, or Ruby.","The crime did NOT happen in The Vault, Workshop, or Back Office.","The weapon is one of: Ban Hammer, Pool Cue, Trophy, or Heavy Ashtray.","The Killer is one of: Kass, Seal, Kate, or Sam.","The crime happened in one of: Afterhours, Kitchen, High Roller Room, or Back Room.","The weapon was NOT Ethernet Cable or Letter Opener.","The Killer is NOT Kate or Seal."];
const adj={vault:['control','office'],control:['vault','high','casino'],high:['control','after'],office:['vault','casino','workshop'],casino:['control','office','after','kitchen'],after:['high','casino','back'],workshop:['office','kitchen'],kitchen:['workshop','casino','back'],back:['kitchen','after']};
const startRooms=['vault','high','office','after','workshop','kitchen','back','control'];const shuffle=a=>[...a].sort(()=>Math.random()-.5);const roll=()=>1+Math.floor(Math.random()*6);const $=id=>document.getElementById(id);const roomName=id=>rooms.find(r=>r[0]===id)[1];
const solution={killer:suspects[Math.floor(Math.random()*suspects.length)],weapon:weapons[Math.floor(Math.random()*weapons.length)],room:crimeRooms[Math.floor(Math.random()*crimeRooms.length)]};
const deck=shuffle([...suspects.filter(x=>x!==solution.killer).map(x=>({type:'SUSPECT',name:x})),...weapons.filter(x=>x!==solution.weapon).map(x=>({type:'WEAPON',name:x})),...crimeRooms.filter(x=>x!==solution.room).map(x=>({type:'ROOM',name:x}))]);
const players=suspects.map((name,i)=>({name,room:startRooms[i],role:name===solution.killer?'KILLER':'INVESTIGATOR',hand:[],found:{}}));deck.forEach((c,i)=>players[i%players.length].hand.push(c));
const searchable=rooms.filter(r=>r[0]!=='casino').map(r=>r[0]), shuffledClues=shuffle(clues), clueMap=Object.fromEntries(searchable.map((r,i)=>[r,shuffledClues[i]]));
let state={turn:0,round:1,public:[],passages:true,security:0,acted:false};const me=()=>players[state.turn];
function render(){const board=$('board');board.innerHTML='';rooms.forEach(([id,n,d])=>{const occupants=players.filter(p=>p.room===id);const el=document.createElement('div');el.className='room '+(id==='casino'?'center ':'')+(me().room===id?'current':'');let extra=occupants.map(p=>`<span class="token">${p.name}${p===me()?' • TURN':''}</span>`).join('');if(['vault','back','high','workshop'].includes(id))extra+=`<span class="passage">◈ PASSAGE ${state.passages?'OPEN':'LOCKED'}</span>`;el.innerHTML=`<h2>${n}</h2><p>${d}</p>${extra}`;el.onclick=()=>move(id);board.appendChild(el)});$('location').textContent=roomName(me().room);$('round').textContent=`ROUND ${state.round}`;$('conference').textContent=`CASE CONFERENCE IN ${5-(state.round%5)||5}`;$('turnOwner').textContent=`${me().name}'S TURN`;$('roleTitle').textContent=me().role;$('roleText').textContent=me().role==='KILLER'?'You know WHO: you. You do NOT know WHERE or WITH WHAT. Investigate your own crime before they identify you.':'Find WHO killed them, WHERE it happened, and WITH WHAT.';$('searchBtn').disabled=me().room==='casino'||state.acted;$('suggestBtn').disabled=me().room==='casino'||state.acted;$('flipBtn').classList.toggle('hidden',me().room!=='control');$('flipBtn').disabled=state.acted;renderPlayers();renderPrivate()}
function renderPlayers(){$('players').innerHTML=players.map((p,i)=>`<span class="${i===state.turn?'active-player':''}">${p.name} · ${roomName(p.room)}</span>`).join('')}
function renderPrivate(){const p=me();$('handCount').textContent=`${p.hand.length} CARDS`;$('hand').innerHTML=p.hand.map(c=>`<div class="clue"><b>${c.type}</b> — ${c.name}</div>`).join('')||'<em>No cards.</em>';const entries=Object.entries(p.found);$('evidenceCount').textContent=`${entries.length} / 8`;$('notebook').innerHTML=entries.length?entries.map(([r,c])=>`<div class="clue">${c}<em>Recovered in ${roomName(r)}</em></div>`).join(''):'No evidence recovered yet.';$('publicCount').textContent=`${state.public.length} / 8`;$('caseBoard').innerHTML=state.public.length?state.public.map(c=>`<div class="clue">${c}<em>Origin: UNKNOWN</em></div>`).join(''):'Nothing has entered the public record.'}
function move(to){if(state.acted)return msg('You already acted this turn.');let legal=adj[me().room].includes(to);if(state.passages&&[['vault','back'],['back','vault'],['high','workshop'],['workshop','high']].some(x=>x[0]===me().room&&x[1]===to))legal=true;if(!legal)return msg('That room is not reachable from here.');me().room=to;state.acted=true;msg(`${me().name} moved to ${roomName(to)}.`);render()}
function search(){if(me().room==='casino'||state.acted)return;state.acted=true;const r=roll();if(r===1||r===6){me().found[me().room]=clueMap[me().room];msg(`🎲 ${r} — SUCCESS. Evidence recovered privately.`)}else msg(`🎲 ${r} — NOTHING. Sorry about your luck.`);render()}
function flip(){if(me().room!=='control'||state.acted)return;const r=roll();state.acted=true;if(r===1||r===6){state.passages=!state.passages;state.security=(state.security+1)%3;msg(`🎲 ${r} — SWITCH FLIPPED. Headquarters security configuration changed.`)}else msg(`🎲 ${r} — FAILED. Nobody else knows you tried.`);render()}
function openSuggestion(){if(me().room==='casino'||state.acted)return;$('suspectSelect').innerHTML=suspects.map(x=>`<option>${x}</option>`).join('');$('weaponSelect').innerHTML=weapons.map(x=>`<option>${x}</option>`).join('');$('suggestModal').classList.remove('hidden')}
function suggest(){const s=$('suspectSelect').value,w=$('weaponSelect').value,r=roomName(me().room);$('suggestModal').classList.add('hidden');state.acted=true;let shown=null,who=null;for(let step=1;step<players.length;step++){const p=players[(state.turn+step)%players.length],matches=p.hand.filter(c=>c.name===s||c.name===w||c.name===r);if(matches.length){shown=matches[Math.floor(Math.random()*matches.length)];who=p;break}}if(shown)msg(`${who.name} privately disproved your suggestion by showing: ${shown.type} — ${shown.name}.`);else msg(`Nobody could disprove ${s} + ${w} + ${r}. 👀`);render()}
function endTurn(){state.turn=(state.turn+1)%players.length;state.acted=false;if(state.turn===0){state.round++;if(state.round%5===0)conference()}msg(`${me().name}'s turn.`);render()}
function conference(){const candidates=players.flatMap(p=>Object.values(p.found)).filter(c=>!state.public.includes(c));if(candidates.length){const c=candidates[Math.floor(Math.random()*candidates.length)];state.public.push(c);showModal('⚠ CASE CONFERENCE','EVIDENCE ENTERED INTO THE RECORD',`<p>A verified clue has been forced into public record:</p><p><b>${c}</b></p><p><em>The room it came from remains secret.</em></p>`)}else showModal('⚠ CASE CONFERENCE','NO NEW TESTIMONY','<p>Nobody currently holds an unpublished verified clue. The investigation continues.</p>')}
function showModal(e,t,html){$('modalEyebrow').textContent=e;$('modalTitle').textContent=t;$('modalText').innerHTML=html;$('modal').classList.remove('hidden')}
function msg(t){$('rollResult').textContent=t}
$('searchBtn').onclick=search;$('suggestBtn').onclick=openSuggestion;$('flipBtn').onclick=flip;$('endBtn').onclick=endTurn;$('submitSuggestion').onclick=suggest;$('cancelSuggestion').onclick=()=> $('suggestModal').classList.add('hidden');$('closeModal').onclick=()=> $('modal').classList.add('hidden');render();