const $=id=>document.getElementById(id);
const rooms=[['vault','THE VAULT','Chips, trophies, prizes and Full Tilt history.'],['control','CONTROL ROOM','Security feeds, servers and building controls.'],['high','HIGH ROLLER ROOM','Private tables. Expensive mistakes.'],['office','BACK OFFICE','Paperwork, cash counter and things nobody explains.'],['casino','CASINO FLOOR','The heart of Headquarters. No evidence is hidden here.'],['after','AFTERHOURS','Bar, pool table, couches and abandoned drinks.'],['workshop','WORKSHOP','Repairs, tools and unfinished projects.'],['kitchen','KITCHEN','Takeout, dirty dishes and one deeply suspicious pot.'],['back','BACK ROOM','Nobody seems willing to explain this room.']];
const suspects=['Sam','Kass','Michael','Ruby','Seal','Kate','REM','Tweeky'];
const weapons=['Casino Chips','Ban Hammer','Broken Bottle','Pool Cue','Ethernet Cable','Trophy','Wrench','Heavy Ashtray','Letter Opener'];
const crimeRooms=['THE VAULT','CONTROL ROOM','HIGH ROLLER ROOM','BACK OFFICE','AFTERHOURS','WORKSHOP','KITCHEN','BACK ROOM'];
const roomName=id=>rooms.find(r=>r[0]===id)?.[1]||id;
const storeKey='kau.session.v1';
let session=JSON.parse(localStorage.getItem(storeKey)||'null'),state=null,pollTimer=null,clockTimer=null,busy=false;
if(!session?.code||!session?.playerToken)location.href='lobby.html';
const apiBase=location.origin;
async function req(action,body){const res=await fetch(`${apiBase}/api/lobby/${session.code}/${action}`,{method:action==='state'?'GET':'POST',headers:{'content-type':'application/json','authorization':`Bearer ${session.playerToken}`},body:action==='state'?undefined:JSON.stringify(body||{})});const data=await res.json().catch(()=>({error:'Invalid server response'}));if(!res.ok)throw new Error(data.error||`Request failed (${res.status})`);return data}
function setResult(t){$('result').textContent=t||''}
async function refresh(){try{const data=await req('state');state=data;render();$('serverState').textContent=`${state.securityName} · PASSAGES ${state.passages?'OPEN':'LOCKED'}`}catch(e){$('serverState').textContent='CONNECTION LOST';setResult(e.message)}}
function isMyTurn(){return state?.turnPlayerId===state?.private?.id&&state.status==='ACTIVE'&&state.phase!=='CONFERENCE'}
function renderClock(){if(!state)return;const remain=Math.max(0,Math.ceil(((state.deadline||Date.now())-Date.now())/1000));$('timer').textContent=state.status==='ACTIVE'?(state.phase==='CONFERENCE'?`Conference closes in ${remain}s`:`Turn timer: ${remain}s`):''}
function render(){if(!state)return;const p=state.private,myTurn=isMyTurn(),conference=state.phase==='CONFERENCE';$('round').textContent=`ROUND ${state.round}`;$('turnOwner').textContent=conference?'CASE CONFERENCE':`${state.players.find(x=>x.id===state.turnPlayerId)?.name?.toUpperCase()||'—'}'S TURN`;$('roleTitle').textContent=p.role||'—';$('roleText').textContent=p.role==='KILLER'?`You are ${p.character}. You know WHO because it is you. Find WHERE and WITH WHAT before they find you.`:`You are ${p.character||'—'}. Find WHO + WHERE + WITH WHAT.`;$('location').textContent=roomName(p.room);$('turnText').textContent=conference?'Headquarters has stopped play. Everyone must vote for who testifies.':myTurn?`Your turn · ${state.phase}`:`Waiting for ${state.players.find(x=>x.id===state.turnPlayerId)?.name||'another player'}…`;
 const board=$('board');board.innerHTML='';for(const [id,n,d] of rooms){const occupants=state.players.filter(x=>x.room===id),reachable=!conference&&!!state.reachable?.[id];const el=document.createElement('div');el.className='room '+(id==='casino'?'center ':'')+(p.room===id?'current ':'')+(reachable?'reachable ':'');let extra=occupants.map(x=>`<span class="token">${x.name}${x.id===p.id?' · YOU':''}${!x.connected?' · OFFLINE':''}</span>`).join('');if(reachable)extra+=`<span class="route">${state.reachable[id].length} STEP${state.reachable[id].length===1?'':'S'}</span>`;if(['vault','back','high','workshop'].includes(id))extra+=`<span class="passage">◈ PASSAGE ${state.passages?'OPEN':'LOCKED'}</span>`;el.innerHTML=`<h2>${n}</h2><p>${d}</p>${extra}`;if(reachable)el.onclick=()=>act('move',{room:id},data=>`Moved via ${data.path.map(roomName).join(' → ')}.`);board.appendChild(el)}
 $('players').innerHTML=state.players.map(x=>`<span class="${x.id===state.turnPlayerId&&!conference?'active-player':''}">${x.name} · ${roomName(x.room)}${x.revealedHand?' · HAND EXPOSED':''}${!x.connected?' · OFFLINE':''}</span>`).join('');
 $('feed').innerHTML=(state.events||[]).map(e=>`<div class="feed-item"><b>${new Date(e.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</b><span>${e.text}</span></div>`).join('')||'<em>No public events yet.</em>';
 $('handCount').textContent=`${p.hand.length} CARDS`;$('hand').innerHTML=p.hand.map(c=>`<div class="clue"><b>${c.type}</b> — ${c.name}</div>`).join('')||'<em>No cards.</em>';
 const found=Object.entries(p.found||{});$('evidenceCount').textContent=`${found.length} / 8`;$('evidence').innerHTML=found.map(([r,c])=>`<div class="clue">${c}<em>Recovered in ${roomName(r)}</em></div>`).join('')||'<em>No evidence recovered.</em>';
 $('historyCount').textContent=`${p.history.length}`;$('history').innerHTML=p.history.map(h=>`<div class="clue"><b>R${h.round}</b> ${h.suspect} · ${h.weapon} · ${h.room}<em>${h.shownBy?`${h.shownBy} showed ${h.shownCard.type}: ${h.shownCard.name}`:'Nobody disproved'}${h.passed?.length?` · Passed: ${h.passed.join(', ')}`:''}</em></div>`).join('')||'<em>No suggestions yet.</em>';
 $('publicCount').textContent=`${state.publicClues.length} / 8`;$('publicBoard').innerHTML=(state.publicClues.map(c=>`<div class="clue">${c}<em>Origin: UNKNOWN</em></div>`).join('')||'<em>No public evidence yet.</em>')+(state.publicHands||[]).map(h=>`<div class="clue"><b>EXPOSED HAND</b> — ${h}</div>`).join('');
 const roomAction=myTurn&&state.phase!=='MOVE'&&!state.acted;$('rollBtn').disabled=!myTurn||state.phase!=='START'||busy;$('searchBtn').disabled=!roomAction||p.room==='casino'||busy;$('suggestBtn').disabled=!roomAction||p.room==='casino'||busy;$('doorsBtn').disabled=!roomAction||p.room!=='control'||busy;$('passagesBtn').disabled=!roomAction||p.room!=='control'||busy;$('endBtn').disabled=!myTurn||state.phase==='MOVE'||busy;const accuseOK=myTurn&&p.knowledge>=3&&!p.accuseLocked&&!busy;$('accuseBtn').disabled=!accuseOK;$('accuseBtn').textContent=accuseOK?(p.role==='KILLER'?'🩸 COVER YOUR TRACKS':'⚠ MAKE ACCUSATION'):`🔒 ACCUSATION (${p.knowledge}/3)`;
 $('conferenceCard').classList.toggle('hidden',!conference);if(conference){$('voteProgress').textContent=`${state.conference?.voteCount||0} / ${state.conference?.total||state.players.length} VOTED`;$('voteTargets').innerHTML=state.players.map(x=>`<button class="vote-target ${state.conference?.voted?'locked':''}" data-id="${x.id}" ${state.conference?.voted||busy?'disabled':''}>${x.name}</button>`).join('');document.querySelectorAll('.vote-target').forEach(btn=>btn.onclick=()=>act('vote',{target:btn.dataset.id},d=>setResult(d.resolved?'Conference resolved.':'Vote submitted.')))}
 renderClock();
}
async function act(action,body,onDone){if(busy)return;busy=true;render();try{const data=await req(action,body);state=data.state||state;if(onDone)onDone(data);else if(action==='roll')setResult(`🎲 ${data.roll}. Choose a highlighted destination.`);else if(action==='search')setResult(data.success?`🎲 ${data.roll} — SUCCESS. ${data.clue}`:`🎲 ${data.roll} — NOTHING. Sorry about your luck.`);else if(action==='switch')setResult(`🎲 ${data.roll} — ${data.privateMessage}`);else if(action==='end')setResult('Turn ended.');render()}catch(e){setResult(e.message)}finally{busy=false;render()}}
function openSuggest(){$('suspectSelect').innerHTML=suspects.map(x=>`<option>${x}</option>`).join('');$('weaponSelect').innerHTML=weapons.map(x=>`<option>${x}</option>`).join('');$('suggestModal').classList.remove('hidden')}
function openAccuse(){const killer=state.private.role==='KILLER';$('accuseTitle').textContent=killer?'COVER YOUR TRACKS':'MAKE AN ACCUSATION';$('accuseSuspect').innerHTML=suspects.map(x=>`<option ${killer&&x===state.private.character?'selected':''}>${x}</option>`).join('');$('accuseSuspect').disabled=killer;$('accuseWeapon').innerHTML=weapons.map(x=>`<option>${x}</option>`).join('');$('accuseRoom').innerHTML=crimeRooms.map(x=>`<option>${x}</option>`).join('');$('accuseModal').classList.remove('hidden')}
$('rollBtn').onclick=()=>act('roll');$('searchBtn').onclick=()=>act('search');$('suggestBtn').onclick=openSuggest;$('doorsBtn').onclick=()=>act('switch',{type:'doors'});$('passagesBtn').onclick=()=>act('switch',{type:'passages'});$('endBtn').onclick=()=>act('end');$('accuseBtn').onclick=openAccuse;
$('cancelSuggest').onclick=()=> $('suggestModal').classList.add('hidden');$('submitSuggest').onclick=()=>{const suspect=$('suspectSelect').value,weapon=$('weaponSelect').value;$('suggestModal').classList.add('hidden');act('suggest',{suspect,weapon},d=>setResult(d.shownCard?`${d.shownBy} privately showed you ${d.shownCard.type}: ${d.shownCard.name}.`:'Nobody could disprove your suggestion. 👀'))};
$('cancelAccuse').onclick=()=> $('accuseModal').classList.add('hidden');$('submitAccuse').onclick=()=>{const body={suspect:$('accuseSuspect').value,weapon:$('accuseWeapon').value,room:$('accuseRoom').value};$('accuseModal').classList.add('hidden');act('accuse',body,d=>{if(d.correct)setResult(`CASE CLOSED. ${d.winner} wins. ${d.solution.killer} · ${d.solution.weapon} · ${d.solution.room}`);else setResult(`WRONG. Penalty roll ${d.penalty}: hand ${d.outcome.toLowerCase()}.`)})};
refresh();pollTimer=setInterval(refresh,1000);clockTimer=setInterval(renderClock,250);