const SUSPECTS=['Sam','Kass','Michael','Ruby','Seal','Kate','REM','Tweeky'];
const WEAPONS=['Casino Chips','Ban Hammer','Broken Bottle','Pool Cue','Ethernet Cable','Trophy','Wrench','Heavy Ashtray','Letter Opener'];
const ROOM_IDS=['vault','control','high','office','casino','after','workshop','kitchen','back'];
const SEARCH_ROOM_IDS=ROOM_IDS.filter(x=>x!=='casino');
const ROOM_NAMES={vault:'THE VAULT',control:'CONTROL ROOM',high:'HIGH ROLLER ROOM',office:'BACK OFFICE',casino:'CASINO FLOOR',after:'AFTERHOURS',workshop:'WORKSHOP',kitchen:'KITCHEN',back:'BACK ROOM'};
const ROOMS=SEARCH_ROOM_IDS.map(x=>ROOM_NAMES[x]);
const ROOM_EDGES=[['vault','control'],['vault','office'],['control','high'],['control','casino'],['high','after'],['office','casino'],['office','workshop'],['casino','after'],['casino','kitchen'],['after','back'],['workshop','kitchen'],['kitchen','back']];
const SECURITY=[{name:'OPEN FLOOR',blocked:[]},{name:'NORTH LOCKDOWN',blocked:[['vault','control'],['control','high']]},{name:'SERVICE LOCKDOWN',blocked:[['office','workshop'],['kitchen','back']]},{name:'EAST LOCKDOWN',blocked:[['high','after'],['after','back']]}];
const BOT_NAMES=['Tony [BOT]','Vanta [BOT]','House Bot','Dealer Bot'];
const TURN_MS=45000,DISCUSSION_MS=60000,VOTE_MS=30000,TESTIMONY_MS=25000,CORRIDOR_TILES=8;
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,x-host-token','access-control-allow-methods':'GET,POST,OPTIONS'}});
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
const d6=()=>Math.floor(Math.random()*6)+1,edge=(a,b)=>[a,b].sort().join('|');
const id=(n=24)=>{const b=new Uint8Array(n);crypto.getRandomValues(b);return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')};
const code=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789',b=new Uint8Array(6);crypto.getRandomValues(b);return[...b].map(x=>a[x%a.length]).join('')};
async function getBody(r){try{return await r.json()}catch{return{}}}
const clean=v=>String(v||'Player').replace(/[<>]/g,'').trim().slice(0,24)||'Player';
function makeBoard(){const graph=Object.fromEntries(ROOM_IDS.map(r=>[r,[]])),tiles={},connections={};for(const[a,b]of ROOM_EDGES){const key=edge(a,b),ids=[];for(let i=1;i<=CORRIDOR_TILES;i++){const t=`tile:${key}:${i}`;ids.push(t);graph[t]=[];tiles[t]={id:t,connection:key,index:i,total:CORRIDOR_TILES,a,b}}const chain=[a,...ids,b];connections[key]={a,b,tiles:ids};for(let i=0;i<chain.length-1;i++){graph[chain[i]].push(chain[i+1]);graph[chain[i+1]].push(chain[i])}}return{graph,tiles,connections}}
const BOARD=makeBoard(),isRoom=x=>ROOM_IDS.includes(x),midTile=(a,b,n=4)=>`tile:${edge(a,b)}:${n}`;
const START_POSITIONS=[midTile('vault','control'),midTile('control','high'),midTile('high','after'),midTile('after','back'),midTile('back','kitchen'),midTile('kitchen','workshop'),midTile('workshop','office'),midTile('office','vault')];
export default{async fetch(r,env){if(r.method==='OPTIONS')return json({ok:true});const u=new URL(r.url);if(u.pathname==='/api/health')return json({ok:true,game:'KILLER AMONG US',multiplayer:'pass-21-bot-conferences'});if(u.pathname==='/api/lobby/create'&&r.method==='POST'){const b=await getBody(r),c=code(),s=env.MATCHES.get(env.MATCHES.idFromName(c));return s.fetch(new Request(`${u.origin}/create`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:c,name:b.name})}))}const m=u.pathname.match(/^\/api\/lobby\/([A-Z0-9]{6})(?:\/(join|state|start|leave|roll|move|search|switch|end|accuse|vote|testify))?$/i);if(m){const s=env.MATCHES.get(env.MATCHES.idFromName(m[1].toUpperCase()));return s.fetch(new Request(`${u.origin}/${m[2]||'state'}`,{method:r.method,headers:r.headers,body:['GET','HEAD'].includes(r.method)?undefined:r.body}))}if(env.ASSETS)return env.ASSETS.fetch(r);return new Response('Not found',{status:404})}};
export class MatchLobby{
constructor(state,env){this.state=state;this.env=env;this.data=null}
async load(){if(!this.data)this.data=await this.state.storage.get('match')||null;return this.data}
async save(){await this.state.storage.put('match',this.data)}
token(r){const x=r.headers.get('authorization')||'';return x.toLowerCase().startsWith('bearer ')?x.slice(7).trim():''}
player(t){return this.data?.players.find(p=>p.token===t)}
normalizePlayer(p){if(!p.position)p.position=p.room||START_POSITIONS[p.seat%START_POSITIONS.length]||'casino';p.room=isRoom(p.position)?p.position:null}
pub(p){this.normalizePlayer(p);return{id:p.id,name:p.name,seat:p.seat,character:p.character||null,room:p.room,position:p.position,connected:p.bot?true:Date.now()-(p.lastSeen||0)<15000,revealedHand:!!p.revealedHand,bot:!!p.bot}}
event(text,type='PUBLIC'){this.data.events=this.data.events||[];this.data.events.unshift({id:id(5),at:Date.now(),text,type});this.data.events=this.data.events.slice(0,60);this.data.version++}
blockedConnection(key){return SECURITY[this.data.security].blocked.some(e=>edge(...e)===key)}
neighbors(pos){let out=[...(BOARD.graph[pos]||[])];out=out.filter(next=>{const here=BOARD.tiles[pos],there=BOARD.tiles[next],tile=here||there;if(!tile||!this.blockedConnection(tile.connection))return true;return!!here});if(this.data.passages){if(pos==='vault')out.push('back');if(pos==='back')out.push('vault');if(pos==='high')out.push('workshop');if(pos==='workshop')out.push('high')}return[...new Set(out)]}
reachable(start,max,moverId){const out={},q=[[start,[]]],best={[start]:0},occupied=new Set(this.data.players.filter(p=>p.id!==moverId&&!isRoom(p.position)).map(p=>p.position));while(q.length){const[n,p]=q.shift();if(p.length>=max)continue;for(const x of this.neighbors(n)){const np=[...p,x],d=np.length;if(best[x]!=null&&best[x]<=d)continue;best[x]=d;if(x!==start&&(!occupied.has(x)||isRoom(x)))out[x]=np;if(isRoom(x)&&x!==start)continue;q.push([x,np])}}return out}
knowledge(p){return new Set([...Object.values(p.found||{}),...(this.data.publicClues||[])]).size}
fresh(p){return[...new Set(Object.values(p.found||{}))].filter(c=>!this.data.publicClues.includes(c))}
addTestBots(){while(this.data.players.length<3){const i=this.data.players.length-1,name=BOT_NAMES[i%BOT_NAMES.length];this.data.players.push({id:id(8),name,seat:this.data.players.length,token:`bot-${id(6)}`,lastSeen:Date.now(),hand:[],found:{},bot:true})}this.event('🤖 Temporary test bots joined the lobby. They take automated turns and participate in Case Conferences.','SYSTEM')}
allCases(){const out=[];for(const killer of SUSPECTS)for(const weapon of WEAPONS)for(const room of ROOMS)out.push({killer,weapon,room});return out}
makeEvidence(){const sol=this.data.solution,sBad=shuffle(SUSPECTS.filter(x=>x!==sol.killer)),wBad=shuffle(WEAPONS.filter(x=>x!==sol.weapon)),rBad=shuffle(ROOMS.filter(x=>x!==sol.room));const defs=[{text:`The Killer is NOT ${sBad.slice(0,4).join(', ')}.`,test:c=>!sBad.slice(0,4).includes(c.killer)},{text:`The Killer is one of: ${shuffle([sol.killer,...sBad.slice(4,7)]).join(', ')}.`,test:c=>[sol.killer,...sBad.slice(4,7)].includes(c.killer)},{text:`The Killer is NOT ${sBad.slice(4,7).join(', ')}.`,test:c=>!sBad.slice(4,7).includes(c.killer)},{text:`The murder weapon was NOT ${wBad.slice(0,4).join(', ')}.`,test:c=>!wBad.slice(0,4).includes(c.weapon)},{text:`The weapon is one of: ${shuffle([sol.weapon,...wBad.slice(4,7)]).join(', ')}.`,test:c=>[sol.weapon,...wBad.slice(4,7)].includes(c.weapon)},{text:`The murder weapon was NOT ${wBad.slice(4,8).join(', ')}.`,test:c=>!wBad.slice(4,8).includes(c.weapon)},{text:`The crime did NOT happen in ${rBad.slice(0,4).join(', ')}.`,test:c=>!rBad.slice(0,4).includes(c.room)},{text:`The crime did NOT happen in ${rBad.slice(4,7).join(', ')}.`,test:c=>!rBad.slice(4,7).includes(c.room)}];const left=this.allCases().filter(c=>defs.every(d=>d.test(c)));if(left.length!==1||left[0].killer!==sol.killer||left[0].weapon!==sol.weapon||left[0].room!==sol.room)throw new Error('Evidence validation failed');return Object.fromEntries(SEARCH_ROOM_IDS.map((r,i)=>[r,defs[i].text]))}
caseMatchesClue(text,c){let m;if((m=text.match(/^The Killer is NOT (.+)\.$/)))return!m[1].split(', ').includes(c.killer);if((m=text.match(/^The Killer is one of: (.+)\.$/)))return m[1].split(', ').includes(c.killer);if((m=text.match(/^The murder weapon was NOT (.+)\.$/)))return!m[1].split(', ').includes(c.weapon);if((m=text.match(/^The weapon is one of: (.+)\.$/)))return m[1].split(', ').includes(c.weapon);if((m=text.match(/^The crime did NOT happen in (.+)\.$/)))return!m[1].split(', ').includes(c.room);return true}
botCandidates(p){const clues=[...new Set([...Object.values(p.found||{}),...(this.data.publicClues||[])])],hand=p.hand||[];return this.allCases().filter(c=>{if(p.role==='KILLER'&&c.killer!==p.character)return false;if(hand.some(h=>(h.type==='SUSPECT'&&c.killer===h.name)||(h.type==='WEAPON'&&c.weapon===h.name)||(h.type==='ROOM'&&c.room===h.name)))return false;return clues.every(x=>this.caseMatchesClue(x,c))})}
distance(start,target){if(start===target)return 0;const q=[[start,0]],seen=new Set([start]);while(q.length){const[n,d]=q.shift();for(const x of this.neighbors(n)){if(x===target)return d+1;if(seen.has(x))continue;seen.add(x);q.push([x,d+1])}}return 999}
botDestination(p,reachable){const entries=Object.entries(reachable);if(!entries.length)return null;const wanted=SEARCH_ROOM_IDS.filter(r=>!p.found?.[r]);const rooms=entries.filter(([x])=>isRoom(x));const freshRooms=rooms.filter(([x])=>wanted.includes(x));if(freshRooms.length)return freshRooms.sort((a,b)=>a[1].length-b[1].length)[0][0];if(rooms.length&&Math.random()<.35)return rooms.sort((a,b)=>a[1].length-b[1].length)[0][0];const targets=wanted.length?wanted:SEARCH_ROOM_IDS;let best=null,bestScore=1e9;for(const[x,path]of entries){if(isRoom(x)&&p.found?.[x])continue;const score=Math.min(...targets.map(t=>this.distance(x,t)))-path.length*.02;if(score<bestScore){bestScore=score;best=x}}return best||entries[Math.floor(Math.random()*entries.length)][0]}
botSearch(p){if(!p.room||p.room==='casino')return;const n=d6();let clue=null,isNew=false;if(n===1||n===6){clue=this.data.clueMap[p.room];isNew=!p.found[p.room];p.found[p.room]=clue;if(isNew&&p.accuseLocked)p.accuseLocked=false}this.event(`🤖 ${p.name} searched ${ROOM_NAMES[p.room]} and rolled ${n}${clue?' — evidence found.':' — found nothing.'}`)}
botAccuseIfCertain(p){if(this.knowledge(p)<3||p.accuseLocked||!p.room)return false;const candidates=this.botCandidates(p);if(candidates.length!==1)return false;const c=candidates[0],correct=c.killer===this.data.solution.killer&&c.weapon===this.data.solution.weapon&&c.room===this.data.solution.room;if(!correct)return false;this.data.status='FINISHED';this.data.deadline=null;this.data.finalSolution=this.data.solution;this.event(p.role==='KILLER'?`🤖 ${p.name} reconstructed the crime, covered their tracks, and won.`:`🤖 ${p.name} solved the case — Investigators win.`,'SYSTEM');return true}
botTurn(p){const n=d6(),reachable=this.reachable(p.position,n,p.id);this.event(`🤖 ${p.name} rolled ${n} for movement.`);const target=this.botDestination(p,reachable);if(target){const path=reachable[target];p.position=target;p.room=isRoom(target)?target:null;this.event(isRoom(target)?`🤖 ${p.name} entered ${ROOM_NAMES[target]}.`:`🤖 ${p.name} moved ${path.length} space${path.length===1?'':'s'} through Headquarters.`)}if(this.botAccuseIfCertain(p))return;if(p.room&&p.room!=='casino')this.botSearch(p);if(this.botAccuseIfCertain(p))return;this.event(`🤖 ${p.name} ended their turn.`)}
advanceOne(){this.data.turn=(this.data.turn+1)%this.data.players.length;const wrapped=this.data.turn===0;this.data.phase='START';this.data.reachable={};this.data.acted=false;if(wrapped){this.data.round++;if((this.data.round-1)%6===0){this.startConference();return'CONFERENCE'}}return wrapped?'WRAPPED':'NEXT'}
runBots(){let guard=0;while(this.data.status==='ACTIVE'&&!['DISCUSSION','VOTING','TESTIMONY'].includes(this.data.phase)&&this.data.players[this.data.turn]?.bot&&guard<this.data.players.length){const p=this.data.players[this.data.turn];this.botTurn(p);if(this.data.status!=='ACTIVE')return;const r=this.advanceOne();if(r==='CONFERENCE')return;guard++}if(this.data.status==='ACTIVE'&&!['DISCUSSION','VOTING','TESTIMONY'].includes(this.data.phase)){this.data.deadline=Date.now()+TURN_MS;this.event(`${this.data.players[this.data.turn].name}'s turn.`,'SYSTEM')}}
botConferenceVotes(){if(this.data.phase!=='VOTING'||!this.data.conference)return;for(const bot of this.data.players.filter(x=>x.bot)){if(this.data.conference.votes[bot.id])continue;const candidates=this.data.players.filter(x=>x.id!==bot.id);if(!candidates.length)continue;const withFresh=candidates.filter(x=>this.fresh(x).length);const pool=withFresh.length&&Math.random()<.65?withFresh:candidates;const target=pool[Math.floor(Math.random()*pool.length)];this.data.conference.votes[bot.id]=target.id;bot.voteTarget=target.id;this.event(`🤖 ${bot.name} cast a Case Conference vote.`,'SYSTEM')}}
async openVoting(){if(this.data.phase!=='DISCUSSION')return;this.data.phase='VOTING';this.data.conference.stage='VOTING';this.data.deadline=Date.now()+VOTE_MS;this.data.conference.deadline=this.data.deadline;this.event('🗳️ ONE MINUTE IS UP — vote for one player to reveal NEW evidence.','SYSTEM');this.botConferenceVotes();const humans=this.data.players.filter(x=>!x.bot).length;if(!humans)await this.resolveVote()}
async deadline(){if(this.data?.status!=='ACTIVE'||!this.data.deadline||Date.now()<this.data.deadline)return;if(this.data.phase==='DISCUSSION'){await this.openVoting();await this.save();return}if(this.data.phase==='VOTING'){await this.resolveVote();return}if(this.data.phase==='TESTIMONY'){await this.autoTestify();return}const p=this.data.players[this.data.turn];this.event(`${p.name} ran out of time. Turn auto-ended.`,'SYSTEM');const r=this.advanceOne();if(r!=='CONFERENCE')this.runBots();await this.save()}
async fetch(r){const u=new URL(r.url),a=u.pathname.slice(1);if(r.method==='OPTIONS')return json({ok:true});if(a==='create'&&r.method==='POST'){if(await this.load())return json({error:'Lobby exists'},409);const b=await getBody(r),now=Date.now(),hostToken=id(),playerToken=id();this.data={code:b.code,status:'LOBBY',hostToken,version:1,players:[{id:id(8),name:clean(b.name||'Host'),seat:0,token:playerToken,lastSeen:now,hand:[],found:{}}],turn:0,round:1,publicClues:[],publicHands:[],security:0,passages:true,phase:'START',reachable:{},acted:false,events:[],deadline:null,conference:null};this.event('Lobby created.','SYSTEM');await this.save();return json({ok:true,code:b.code,hostToken,playerToken,playerId:this.data.players[0].id})}if(!await this.load())return json({error:'Lobby not found'},404);this.data.players.forEach(p=>this.normalizePlayer(p));if(a==='join'&&r.method==='POST'){if(this.data.status!=='LOBBY')return json({error:'Match already started'},409);if(this.data.players.length>=8)return json({error:'Lobby full'},409);const b=await getBody(r),name=clean(b.name);if(this.data.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return json({error:'Name already used'},409);const p={id:id(8),name,seat:this.data.players.length,token:id(),lastSeen:Date.now(),hand:[],found:{}};this.data.players.push(p);this.event(`${name} joined.`);await this.save();return json({ok:true,code:this.data.code,playerToken:p.token,playerId:p.id})}const p=this.player(this.token(r));if(!p)return json({error:'Invalid player session'},401);p.lastSeen=Date.now();await this.deadline();if(a==='state'&&r.method==='GET'){await this.save();return json(this.view(p))}if(a==='leave'&&r.method==='POST'){if(this.data.status!=='LOBBY')return json({error:'Cannot leave after start'},409);this.data.players=this.data.players.filter(x=>x.id!==p.id);this.data.players.forEach((x,i)=>x.seat=i);this.event(`${p.name} left.`);await this.save();return json({ok:true})}if(a==='start'&&r.method==='POST'){if(r.headers.get('x-host-token')!==this.data.hostToken)return json({error:'Host required'},403);if(this.data.status!=='LOBBY')return json({ok:true,alreadyStarted:true,state:this.view(p)});if(this.data.players.length<3)this.addTestBots();this.start();await this.save();return json({ok:true,state:this.view(p)})}if(this.data.status!=='ACTIVE')return json({error:'Match is not active'},409);if(a==='vote')return this.vote(p,await getBody(r));if(a==='testify')return this.testify(p,await getBody(r));if(['DISCUSSION','VOTING','TESTIMONY'].includes(this.data.phase))return json({error:'Case Conference is in progress'},409);if(this.data.players[this.data.turn]?.id!==p.id)return json({error:'It is not your turn'},409);if(a==='roll')return this.roll(p);if(a==='move')return this.move(p,await getBody(r));if(a==='search')return this.search(p);if(a==='switch')return this.flip(p,await getBody(r));if(a==='accuse')return this.accuse(p,await getBody(r));if(a==='end')return this.end(p);return json({error:'Not found'},404)}
start(){const chars=shuffle(SUSPECTS).slice(0,this.data.players.length),ki=Math.floor(Math.random()*this.data.players.length),killer=chars[ki],weapon=WEAPONS[Math.floor(Math.random()*WEAPONS.length)],room=ROOMS[Math.floor(Math.random()*ROOMS.length)],deck=shuffle([...chars.filter(x=>x!==killer).map(name=>({type:'SUSPECT',name})),...WEAPONS.filter(x=>x!==weapon).map(name=>({type:'WEAPON',name})),...ROOMS.filter(x=>x!==room).map(name=>({type:'ROOM',name}))]);this.data.players.forEach((p,i)=>{p.character=chars[i];p.role=i===ki?'KILLER':'INVESTIGATOR';p.position=START_POSITIONS[i%START_POSITIONS.length];p.room=null;p.hand=[];p.found={};p.accuseLocked=false;p.revealedHand=false;p.voteTarget=null});deck.forEach((c,i)=>this.data.players[i%this.data.players.length].hand.push(c));this.data.solution={killer,weapon,room};this.data.clueMap=this.makeEvidence();this.data.status='ACTIVE';this.data.turn=this.data.players.findIndex(p=>!p.bot);if(this.data.turn<0)this.data.turn=0;this.data.round=1;this.data.phase='START';this.data.reachable={};this.data.acted=false;this.data.publicClues=[];this.data.publicHands=[];this.data.security=0;this.data.passages=true;this.data.deadline=Date.now()+TURN_MS;this.event(`Investigation begins. Everyone starts in the outer hallways. ${this.data.players[this.data.turn].name}'s turn.`,'SYSTEM')}
async roll(p){if(this.data.phase!=='START')return json({error:'Already rolled'},409);const n=d6();this.data.reachable=this.reachable(p.position,n,p.id);this.data.phase=Object.keys(this.data.reachable).length?'MOVE':'ROOM';this.event(`${p.name} rolled ${n} for movement.`);await this.save();return json({ok:true,roll:n,reachable:this.data.reachable,state:this.view(p)})}
async move(p,b){const target=String(b.position||b.room||'');if(this.data.phase!=='MOVE'||!this.data.reachable[target])return json({error:'Space not reachable'},409);if(!isRoom(target)&&this.data.players.some(x=>x.id!==p.id&&x.position===target))return json({error:'That hallway tile is occupied'},409);const path=this.data.reachable[target];p.position=target;p.room=isRoom(target)?target:null;this.data.phase='ROOM';this.data.reachable={};this.event(isRoom(target)?`${p.name} entered ${ROOM_NAMES[target]}. Movement ends on room entry.`:`${p.name} moved through Headquarters.`);await this.save();return json({ok:true,path,position:target,state:this.view(p)})}
async search(p){if(this.data.phase==='MOVE'||this.data.acted)return json({error:'Cannot search now'},409);if(!p.room)return json({error:'You must be inside a room to search'},409);if(p.room==='casino')return json({error:'Casino Floor has no evidence'},409);const n=d6();this.data.acted=true;let clue=null,isNew=false;if(n===1||n===6){clue=this.data.clueMap[p.room];isNew=!p.found[p.room];p.found[p.room]=clue;if(isNew&&p.accuseLocked)p.accuseLocked=false}this.event(`${p.name} searched ${ROOM_NAMES[p.room]}.`);await this.save();return json({ok:true,roll:n,success:!!clue,isNew,clue,state:this.view(p)})}
async flip(p,b){if(p.room!=='control'||this.data.phase==='MOVE'||this.data.acted)return json({error:'Cannot use Control Room now'},409);const type=b.type==='passages'?'passages':'doors',n=d6(),success=n===1||n===6;this.data.acted=true;if(success){if(type==='passages')this.data.passages=!this.data.passages;else this.data.security=(this.data.security+1)%SECURITY.length}this.event(success?'⚠ Headquarters configuration changed.':`${p.name} used Control Room.`);await this.save();return json({ok:true,roll:n,success,privateMessage:success?'SUCCESS. Headquarters changed.':'FAILED. Nobody else knows you tried.',state:this.view(p)})}
async accuse(p,b){if(this.knowledge(p)<3||p.accuseLocked)return json({error:'Accusation locked'},409);if(!p.room)return json({error:'Enter a room before making an accusation'},409);const suspect=p.role==='KILLER'?p.character:String(b.suspect||''),weapon=String(b.weapon||''),room=String(b.room||'');if(!SUSPECTS.includes(suspect)||!WEAPONS.includes(weapon)||!ROOMS.includes(room))return json({error:'Invalid accusation'},400);const correct=suspect===this.data.solution.killer&&weapon===this.data.solution.weapon&&room===this.data.solution.room;if(correct){this.data.status='FINISHED';this.data.deadline=null;this.data.finalSolution=this.data.solution;this.event(p.role==='KILLER'?`${p.name} discovered WHERE and WITH WHAT, covered their tracks, and won.`:`${p.name} identified the Killer, weapon, and room — Investigators win.`,'SYSTEM');await this.save();return json({ok:true,correct:true,winner:p.name,solution:this.data.solution,state:this.view(p)})}p.accuseLocked=true;this.data.acted=true;const n=d6();let outcome;if(n===1||n===6){p.hand=[];outcome='DISCARDED FACE-DOWN'}else{p.revealedHand=true;outcome='REVEALED';const x=`${p.name}: ${p.hand.map(c=>`${c.type}: ${c.name}`).join(' · ')||'EMPTY HAND'}`;if(!this.data.publicHands.includes(x))this.data.publicHands.push(x)}this.event(`${p.name} made a WRONG accusation.`);await this.save();return json({ok:true,correct:false,penalty:n,outcome,state:this.view(p)})}
async end(p){this.event(`${p.name} ended their turn.`);const r=this.advanceOne();if(r!=='CONFERENCE')this.runBots();await this.save();return json({ok:true,state:this.view(p)})}
startConference(){this.data.phase='DISCUSSION';this.data.conference={stage:'DISCUSSION',votes:{},startedAt:Date.now(),deadline:Date.now()+DISCUSSION_MS,witnessId:null};this.data.deadline=this.data.conference.deadline;this.data.players.forEach(p=>p.voteTarget=null);this.event('🚨 CASE CONFERENCE — ONE MINUTE. Everyone state your case together.','SYSTEM')}
async vote(p,b){if(this.data.phase!=='VOTING')return json({error:'Voting opens after the one-minute discussion'},409);if(p.bot)return json({error:'Bot votes are automatic'},409);const target=this.data.players.find(x=>x.id===String(b.target||''));if(!target)return json({error:'Invalid target'},400);this.data.conference.votes[p.id]=target.id;p.voteTarget=target.id;this.event(`${p.name} voted.`,'SYSTEM');this.botConferenceVotes();const humans=this.data.players.filter(x=>!x.bot).length,humanVotes=Object.keys(this.data.conference.votes).filter(id=>!this.data.players.find(x=>x.id===id)?.bot).length;if(humanVotes>=humans){await this.resolveVote();return json({ok:true,resolved:true,state:this.view(p)})}await this.save();return json({ok:true,resolved:false,state:this.view(p)})}
async resolveVote(){if(this.data.phase!=='VOTING')return;this.botConferenceVotes();const counts={};for(const x of Object.values(this.data.conference.votes||{}))counts[x]=(counts[x]||0)+1;let ids=Object.keys(counts),witness=null;if(ids.length){const top=Math.max(...ids.map(x=>counts[x])),tied=ids.filter(x=>counts[x]===top);witness=this.data.players.find(p=>p.id===tied[Math.floor(Math.random()*tied.length)])}if(!witness){witness=this.data.players[Math.floor(Math.random()*this.data.players.length)]}const f=this.fresh(witness);if(!f.length){this.event(`🔎 ${witness.name} was selected, but holds no unpublished evidence.`,'SYSTEM');this.endConference();await this.save();return}this.data.phase='TESTIMONY';this.data.conference.stage='TESTIMONY';this.data.conference.witnessId=witness.id;this.data.deadline=Date.now()+TESTIMONY_MS;this.data.conference.deadline=this.data.deadline;this.event(`🔎 ${witness.name} must reveal ONE piece of NEW evidence.`,'SYSTEM');if(witness.bot)await this.autoTestify();else await this.save()}
async testify(p,b){if(this.data.phase!=='TESTIMONY'||this.data.conference?.witnessId!==p.id)return json({error:'You are not the witness'},409);const clue=String(b.clue||''),fresh=this.fresh(p);if(!fresh.includes(clue))return json({error:'Choose one of your unpublished evidence clues'},400);this.publishTestimony(p,clue);this.endConference();await this.save();return json({ok:true,state:this.view(p)})}
publishTestimony(p,clue){if(!this.data.publicClues.includes(clue))this.data.publicClues.push(clue);this.event(`📌 ${p.name} revealed NEW evidence. Its room origin remains secret.`,'SYSTEM')}
async autoTestify(){if(this.data.phase!=='TESTIMONY')return;const witness=this.data.players.find(p=>p.id===this.data.conference?.witnessId),f=witness?this.fresh(witness):[];if(witness&&f.length){const clue=f[Math.floor(Math.random()*f.length)];this.publishTestimony(witness,clue);if(witness.bot)this.event(`🤖 ${witness.name} automatically completed testimony.`,'SYSTEM')}else this.event('Testimony expired with no evidence revealed.','SYSTEM');this.endConference();await this.save()}
endConference(){this.data.conference=null;this.data.turn=this.data.players.findIndex(p=>!p.bot);if(this.data.turn<0)this.data.turn=0;this.data.phase='START';this.data.reachable={};this.data.acted=false;this.data.deadline=Date.now()+TURN_MS;this.data.version++;this.event(`${this.data.players[this.data.turn].name}'s turn.`,'SYSTEM')}
view(p){this.normalizePlayer(p);const humans=this.data.players.filter(x=>!x.bot).length,total=this.data.players.length,c=this.data.conference?{stage:this.data.conference.stage,deadline:this.data.conference.deadline,voteCount:Object.keys(this.data.conference.votes||{}).length,total,voted:!!this.data.conference.votes?.[p.id],witnessId:this.data.conference.witnessId||null,myTestimony:this.data.phase==='TESTIMONY'&&this.data.conference.witnessId===p.id?this.fresh(p):[]}:null;return{ok:true,version:this.data.version,code:this.data.code,status:this.data.status,round:this.data.round,phase:this.data.phase,deadline:this.data.deadline,turnPlayerId:this.data.players[this.data.turn]?.id||null,securityName:SECURITY[this.data.security].name,passages:this.data.passages,reachable:this.data.reachable,acted:this.data.acted,players:this.data.players.map(x=>this.pub(x)),publicClues:this.data.publicClues,publicHands:this.data.publicHands,events:this.data.events,conference:c,board:{tiles:BOARD.tiles,connections:BOARD.connections,startPositions:START_POSITIONS},finalSolution:this.data.status==='FINISHED'?this.data.solution:null,private:{id:p.id,name:p.name,character:p.character||null,role:p.role||null,room:p.room||null,position:p.position,hand:p.hand||[],found:p.found||{},knowledge:this.knowledge(p),accuseLocked:!!p.accuseLocked,killerKnowledge:p.role==='KILLER'?{killer:p.character}:null}}}}
